name: restrr
description: Dart package which allows to communicate with the financrr REST API.
version: 0.5.0
repository: https://github.com/financrr/restrr

environment:
  sdk: ^3.2.4

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
dependencies:
  cookie_jar: ^4.0.8
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  logging: ^1.2.0
